CREATE TABLE IF NOT EXISTS usuario(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre  text,
    documento text,
    correo text NOT NULL,
    clave text NOT NULL,
    fecha date NOT NULL,
    estado  BOOLEAN NOT NULL DEFAULT TRUE 
    );
    
INSERT INTO usuario(nombre,documento,correo,clave)
    VALUES('cristian camilo tafue morales','1094964990','cristiancamilotafurmorales@hotmail.com','2019-10-16',true); 
ALTER TABLE usuario ADD estado BOOLEAN;
ALTER TABLE proyecto ADD estado BOOLEAN;
ALTER TABLE proyecto RENAME COLUMN emprededor TO emprendedor;
ALTER TABLE usuario ALTER COLUMN estado SET NOT NULL; 
ALTER TABLE proyecto ALTER COLUMN monto TYPE bigint;

CREATE TABLE IF NOT EXISTS proyecto(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    emprendedor integer ,
    nombre text NOT NULL,
    descripcion text NOT NULL,
  /*documentacion text NOT NULL,*/ 
    presupuesto bigint NOT NULL, 
    presupuestoMinimo bigint NOT NULL, 
    calificacion integer DEFAULT 0, 
    fecha date NOT NULL,
    estado  BOOLEAN NOT NULL 
    );

CREATE TABLE IF NOT EXISTS actividad(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    proyecto integer REFERENCES proyecto(id),
    nombre text not NULL;
    
    
    );

CREATE TABLE IF NOT EXISTS transaccion(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    proyecto integer REFERENCES proyecto(id),
    inversor integer REFERENCES usuario(id),
    monto bigint NOT NULL, 
   /* venficio */
    PRIMARY KEY (id) 
    );
/*donacion*/
 
